### ISSUE TITLE
Place usage of heap behind feature gate

### ISSUE THREAD

**Issue by eupn** [bobbin-rs/bobbin-sdk#10]
@jcsoo we should probably have a "no-heap" feature that gates mention of `Heap` and defines board initialization methods without passing an instance of `Heap` to them.

If you don't mind, I have already implemented this since otherwise building was failing with an error that compiler was unable to find a heap-related (`_sheap`) symbols and can make a PR for this.

**Comment by jcsoo** [comment]
Yes, this would be useful - I've been running into those errors to. Would love to see a PR if you have one!
